DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE` (
  `ID` INT(5) NOT NULL,
  `ROLE` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT  INTO `ROLE`(`ID`,`ROLE`) VALUES (1,'超级管理员'),(2,'子管理员'),(3,'普通用户');