USE `MICROBLOG`
DROP TABLE IF EXISTS `USER_IMG`;
CREATE TABLE `USER_IMG`(
 `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `IMG_PATH` VARCHAR(200) NOT NULL,
  `USER_LOGIN_ID` INT(5) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;