
DROP TABLE IF EXISTS `USER_DAILY_TAGS`;
CREATE TABLE `USER_DAILY_TAGS`(
  `ID` INT(5) NOT NULL AUTO_INCREMENT ,
   `USER_LOGIN_ID` INT(5) NOT NULL,
  `DAILY_ID` INT(5) NOT NULL  ,
   `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;