DROP TABLE IF EXISTS `USER_DAILY_DETAILS`;
CREATE TABLE `USER_DAILY_DETAILS`(
  `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `USER_CATEGORY_ID` INT(5) NOT NULL,
   `DAILY_ID` INT(5) NOT NULL  ,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
